name: "Chromatic Deployment"

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-storybook:
    name: "Deploy Storybook in Chromatic"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Declare commit short SHA variable
        id: commit
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        id: publish
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "A new Storybook preview has been published! :rocket: \n * Storybook preview: https://${{ steps.commit.outputs.sha_short }}--615d643ec68451003a336cee.chromatic.com \n * Chromatic build: ${{ steps.publish.outputs.buildUrl }}"
            })
